server:
  port: 40000

spring:
  application:
    name: PLOUFPLOUF

logging:
  level:
    org.springframework.web: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:30000/eureka/
